### ISSUE TITLE
README / folder structure

### ISSUE THREAD

**Issue by joelpittet** [ubc-web-services/galactus#3]
Could you add a README to indicate what the two themes do and how they relate?

**Comment by occupant** [comment]
Moved the readme to the correct directory (was still in the parent theme directory)

**Comment by joelpittet** [comment]
It may help to move galactus to the main folder as it's the base/parent theme?

**Comment by occupant** [comment]
I was trying to follow what I've seen with other base theme / child theme distributions in drupal (omega, adaptive theme, etc). Somewhere along the line I seem to have added an extra folder there. :/  I'll get that removed.

**Comment by joelpittet** [comment]
That is interesting, I wonder why they set their folders up like that?  `zen` and `bootstrap` structure it more along the lines of the way I was thinking but I'm open to the idea.   Just find it a bit strange to see `themes/custom/galactus/galactus`, though I could be picky;)

http://cgit.drupalcode.org/zen/tree/

**Comment by occupant** [comment]
Agreed, it's weird :)

The nice thing about it though is that there are clearly two themes there - iirc, the install instructions for Zen mention moving STARTERKIT to your theme directory (so the child theme isn't nested inside the base theme). Thinking about themers encountering the theme for the first time, it seems clearer at first glance. Maybe I'm just overthinking it though.

Totally open to adjusting this to any way that makes most sense.

**Comment by joelpittet** [comment]
I agree right now is not great, having them in separate folders `galactus/galactus` and `galactus/ubc-clf` is better. My thought is the hierarchy makes more sense if `galactus` is in the root. I'm not sure why `omega` and `adaptive theme` do it that way.  Let someone else decide, but want me to post the PR for `galactus/galactus`?

**Comment by occupant** [comment]
I think you're right. I've committed the PR, but it's broken PR #8 . I can move the child theme later this afternoon.
