### ISSUE TITLE
Slidein option conflicts with Quick Edit

### ISSUE THREAD

**Issue by occupant** [ubc-web-services/galactus#43]
There may be other libraries that create the same issue.

To reproduce:
- enable galactus, set navigation option to slide in or cover types
- enable quick edit module

Clicking on nav trigger adds `off-canvas-drawer--is-animating` classes, but the `off-canvas-drawer--is-active` don't get applied and the `transitionend` event never fires. The result is a page that is 'locked' into `overflow:none` ~~and the content region is below the off-canvas-mask~~.

**Comment by joelpittet** [comment]
quickedit is deprecated, maybe we can just close this?

**Comment by joelpittet** [comment]
https://www.drupal.org/node/3259831

**Comment by occupant** [comment]
Agreed, outdated. Closed :)
