### ISSUE TITLE
Consider base theme off of classy

### ISSUE THREAD

**Issue by joelpittet** [ubc-web-services/galactus#7]
Though I personally like the control of stable, and I am totally up for a discussion on the merits of both I'm leaning towards classy as a base theme to get some of their defaults, or we may end up copying elements of classy into galactus(which isn't a bad idea and what [basic](https://www.drupal.org/project/basic) theme does)

**Comment by joelpittet** [comment]
Looks like it's now extending classing but excluding the base CSS.

I noticed `less/clf.fixes.less`  `.form--inline .form-item` comes from `/core/themes/classy/css/components/inline-form.css` and maybe we should include that one explicitly and maybe a few others to help with forms like tabledrag and others...  we could do it piece meal the need comes up?

**Comment by occupant** [comment]
This is outdated - I'm going to close this as well
